### ISSUE TITLE
Update app to accommodate message binary layout

### ISSUE THREAD

**Issue by avive** [spacemeshos/ledger-app#1]
See updated spec here: https://github.com/spacemeshos/SMIPS/issues/23
The binary payload that the ledger app will get via the sdk to sign has a modified layout. First 32 bytes is a network id prefix and following that the tx binary payload. So, for example, the tx type is in byte(32) instead of byte(0) in the message.

**Comment by valar999** [comment]
Implemented accordingly in source files
